<?php
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly
class OT_Widgets_Icons {

    public function __construct() {
        
    }


    /**
     * Get list icons
     * @return array icons
     */
    function get_list( $type = false ) {
        if( $type == "themify" ) {
            return $this->themify_icons;
        } elseif( $type == "google" ) {
            return $this->google_icons;
        } else {
            return $this->font_awesome;
        }
        
    }


    /**
     * Themify icon list
     * @var array
     */

    protected $themify_icons = array(
        'no-icon',
        'ti-wand',
        'ti-volume',
        'ti-user',
        'ti-unlock',
        'ti-unlink',
        'ti-trash',
        'ti-thought',
        'ti-target',
        'ti-tag',
        'ti-tablet',
        'ti-star',
        'ti-spray',
        'ti-signal',
        'ti-shopping-cart',
        'ti-shopping-cart-full',
        'ti-settings',
        'ti-search',
        'ti-zoom-in',
        'ti-zoom-out',
        'ti-cut',
        'ti-ruler',
        'ti-ruler-pencil',
        'ti-ruler-alt',
        'ti-bookmark',
        'ti-bookmark-alt',
        'ti-reload',
        'ti-plus',
        'ti-pin',
        'ti-pencil',
        'ti-pencil-alt',
        'ti-paint-roller',
        'ti-paint-bucket',
        'ti-na',
        'ti-mobile',
        'ti-minus',
        'ti-medall',
        'ti-medall-alt',
        'ti-marker',
        'ti-marker-alt',
        'ti-arrow-up',
        'ti-arrow-right',
        'ti-arrow-left',
        'ti-arrow-down',
        'ti-lock',
        'ti-location-arrow',
        'ti-link',
        'ti-layout',
        'ti-layers',
        'ti-layers-alt',
        'ti-key',
        'ti-import',
        'ti-image',
        'ti-heart',
        'ti-heart-broken',
        'ti-hand-stop',
        'ti-hand-open',
        'ti-hand-drag',
        'ti-folder',
        'ti-flag',
        'ti-flag-alt',
        'ti-flag-alt-2',
        'ti-eye',
        'ti-export',
        'ti-exchange-vertical',
        'ti-desktop',
        'ti-cup',
        'ti-crown',
        'ti-comments',
        'ti-comment',
        'ti-comment-alt',
        'ti-close',
        'ti-clip',
        'ti-angle-up',
        'ti-angle-right',
        'ti-angle-left',
        'ti-angle-down',
        'ti-check',
        'ti-check-box',
        'ti-camera',
        'ti-announcement',
        'ti-brush',
        'ti-briefcase',
        'ti-bolt',
        'ti-bolt-alt',
        'ti-blackboard',
        'ti-bag',
        'ti-move',
        'ti-arrows-vertical',
        'ti-arrows-horizontal',
        'ti-fullscreen',
        'ti-arrow-top-right',
        'ti-arrow-top-left',
        'ti-arrow-circle-up',
        'ti-arrow-circle-right',
        'ti-arrow-circle-left',
        'ti-arrow-circle-down',
        'ti-angle-double-up',
        'ti-angle-double-right',
        'ti-angle-double-left',
        'ti-angle-double-down',
        'ti-zip',
        'ti-world',
        'ti-wheelchair',
        'ti-view-list',
        'ti-view-list-alt',
        'ti-view-grid',
        'ti-uppercase',
        'ti-upload',
        'ti-underline',
        'ti-truck',
        'ti-timer',
        'ti-ticket',
        'ti-thumb-up',
        'ti-thumb-down',
        'ti-text',
        'ti-stats-up',
        'ti-stats-down',
        'ti-split-v',
        'ti-split-h',
        'ti-smallcap',
        'ti-shine',
        'ti-shift-right',
        'ti-shift-left',
        'ti-shield',
        'ti-notepad',
        'ti-server',
        'ti-quote-right',
        'ti-quote-left',
        'ti-pulse',
        'ti-printer',
        'ti-power-off',
        'ti-plug',
        'ti-pie-chart',
        'ti-paragraph',
        'ti-panel',
        'ti-package',
        'ti-music',
        'ti-music-alt',
        'ti-mouse',
        'ti-mouse-alt',
        'ti-money',
        'ti-microphone',
        'ti-menu',
        'ti-menu-alt',
        'ti-map',
        'ti-map-alt',
        'ti-loop',
        'ti-location-pin',
        'ti-list',
        'ti-light-bulb',
        'ti-Italic',
        'ti-info',
        'ti-infinite',
        'ti-id-badge',
        'ti-hummer',
        'ti-home',
        'ti-help',
        'ti-headphone',
        'ti-harddrives',
        'ti-harddrive',
        'ti-gift',
        'ti-game',
        'ti-filter',
        'ti-files',
        'ti-file',
        'ti-eraser',
        'ti-envelope',
        'ti-download',
        'ti-direction',
        'ti-direction-alt',
        'ti-dashboard',
        'ti-control-stop',
        'ti-control-shuffle',
        'ti-control-play',
        'ti-control-pause',
        'ti-control-forward',
        'ti-control-backward',
        'ti-cloud',
        'ti-cloud-up',
        'ti-cloud-down',
        'ti-clipboard',
        'ti-car',
        'ti-calendar',
        'ti-book',
        'ti-bell',
        'ti-basketball',
        'ti-bar-chart',
        'ti-bar-chart-alt',
        'ti-back-right',
        'ti-back-left',
        'ti-arrows-corner',
        'ti-archive',
        'ti-anchor',
        'ti-align-right',
        'ti-align-left',
        'ti-align-justify',
        'ti-align-center',
        'ti-alert',
        'ti-alarm-clock',
        'ti-agenda',
        'ti-write',
        'ti-window',
        'ti-widgetized',
        'ti-widget',
        'ti-widget-alt',
        'ti-wallet',
        'ti-video-clapper',
        'ti-video-camera',
        'ti-vector',
        'ti-themify-logo',
        'ti-themify-favicon',
        'ti-themify-favicon-alt',
        'ti-support',
        'ti-stamp',
        'ti-split-v-alt',
        'ti-slice',
        'ti-shortcode',
        'ti-shift-right-alt',
        'ti-shift-left-alt',
        'ti-ruler-alt-2',
        'ti-receipt',
        'ti-pin2',
        'ti-pin-alt',
        'ti-pencil-alt2',
        'ti-palette',
        'ti-more',
        'ti-more-alt',
        'ti-microphone-alt',
        'ti-magnet',
        'ti-line-double',
        'ti-line-dotted',
        'ti-line-dashed',
        'ti-layout-width-full',
        'ti-layout-width-default',
        'ti-layout-width-default-alt',
        'ti-layout-tab',
        'ti-layout-tab-window',
        'ti-layout-tab-v',
        'ti-layout-tab-min',
        'ti-layout-slider',
        'ti-layout-slider-alt',
        'ti-layout-sidebar-right',
        'ti-layout-sidebar-none',
        'ti-layout-sidebar-left',
        'ti-layout-placeholder',
        'ti-layout-menu',
        'ti-layout-menu-v',
        'ti-layout-menu-separated',
        'ti-layout-menu-full',
        'ti-layout-media-right-alt',
        'ti-layout-media-right',
        'ti-layout-media-overlay',
        'ti-layout-media-overlay-alt',
        'ti-layout-media-overlay-alt-2',
        'ti-layout-media-left-alt',
        'ti-layout-media-left',
        'ti-layout-media-center-alt',
        'ti-layout-media-center',
        'ti-layout-list-thumb',
        'ti-layout-list-thumb-alt',
        'ti-layout-list-post',
        'ti-layout-list-large-image',
        'ti-layout-line-solid',
        'ti-layout-grid4',
        'ti-layout-grid3',
        'ti-layout-grid2',
        'ti-layout-grid2-thumb',
        'ti-layout-cta-right',
        'ti-layout-cta-left',
        'ti-layout-cta-center',
        'ti-layout-cta-btn-right',
        'ti-layout-cta-btn-left',
        'ti-layout-column4',
        'ti-layout-column3',
        'ti-layout-column2',
        'ti-layout-accordion-separated',
        'ti-layout-accordion-merged',
        'ti-layout-accordion-list',
        'ti-ink-pen',
        'ti-info-alt',
        'ti-help-alt',
        'ti-headphone-alt',
        'ti-hand-point-up',
        'ti-hand-point-right',
        'ti-hand-point-left',
        'ti-hand-point-down',
        'ti-gallery',
        'ti-face-smile',
        'ti-face-sad',
        'ti-credit-card',
        'ti-control-skip-forward',
        'ti-control-skip-backward',
        'ti-control-record',
        'ti-control-eject',
        'ti-comments-smiley',
        'ti-brush-alt',
        'ti-youtube',
        'ti-vimeo',
        'ti-twitter',
        'ti-time',
        'ti-tumblr',
        'ti-skype',
        'ti-share',
        'ti-share-alt',
        'ti-rocket',
        'ti-pinterest',
        'ti-new-window',
        'ti-microsoft',
        'ti-list-ol',
        'ti-linkedin',
        'ti-layout-sidebar-2',
        'ti-layout-grid4-alt',
        'ti-layout-grid3-alt',
        'ti-layout-grid2-alt',
        'ti-layout-column4-alt',
        'ti-layout-column3-alt',
        'ti-layout-column2-alt',
        'ti-instagram',
        'ti-google',
        'ti-github',
        'ti-flickr',
        'ti-facebook',
        'ti-dropbox',
        'ti-dribbble',
        'ti-apple',
        'ti-android',
        'ti-save',
        'ti-save-alt',
        'ti-yahoo',
        'ti-wordpress',
        'ti-vimeo-alt',
        'ti-twitter-alt',
        'ti-tumblr-alt',
        'ti-trello',
        'ti-stack-overflow',
        'ti-soundcloud',
        'ti-sharethis',
        'ti-sharethis-alt',
        'ti-reddit',
        'ti-pinterest-alt',
        'ti-microsoft-alt',
        'ti-linux',
        'ti-jsfiddle',
        'ti-joomla',
        'ti-html5',
        'ti-flickr-alt',
        'ti-email',
        'ti-drupal',
        'ti-dropbox-alt',
        'ti-css3',
        'ti-rss',
        'ti-rss-alt'

    );

    /**
     * FontAwesome icon list for version 4.1.0.
     * @var array
     */

    protected $font_awesome = array(
        'no icon',
        'fa-adjust',
        'fa-adn',
        'fa-align-center',
        'fa-align-justify',
        'fa-align-left',
        'fa-align-right',
        'fa-ambulance',
        'fa-anchor',
        'fa-android',
        'fa-angellist',
        'fa-angle-double-down',
        'fa-angle-double-left',
        'fa-angle-double-right',
        'fa-angle-double-up',
        'fa-angle-down',
        'fa-angle-left',
        'fa-angle-right',
        'fa-angle-up',
        'fa-apple',
        'fa-archive',
        'fa-area-chart',
        'fa-arrow-circle-down',
        'fa-arrow-circle-left',
        'fa-arrow-circle-o-down',
        'fa-arrow-circle-o-left',
        'fa-arrow-circle-o-right',
        'fa-arrow-circle-o-up',
        'fa-arrow-circle-right',
        'fa-arrow-circle-up',
        'fa-arrow-down',
        'fa-arrow-left',
        'fa-arrow-right',
        'fa-arrow-up',
        'fa-arrows',
        'fa-arrows-alt',
        'fa-arrows-h',
        'fa-arrows-v',
        'fa-asterisk',
        'fa-at',
        'fa-backward',
        'fa-ban',
        'fa-bar-chart',
        'fa-barcode',
        'fa-bars',
        'fa-beer',
        'fa-behance',
        'fa-behance-square',
        'fa-bell',
        'fa-bell-o',
        'fa-bell-slash',
        'fa-bell-slash-o',
        'fa-bicycle',
        'fa-binoculars',
        'fa-birthday-cake',
        'fa-bitbucket',
        'fa-bitbucket-square',
        'fa-bold',
        'fa-bolt',
        'fa-bomb',
        'fa-book',
        'fa-bookmark',
        'fa-bookmark-o',
        'fa-briefcase',
        'fa-btc',
        'fa-bug',
        'fa-building',
        'fa-building-o',
        'fa-bullhorn',
        'fa-bullseye',
        'fa-bus',
        'fa-calculator',
        'fa-calendar',
        'fa-calendar-o',
        'fa-camera',
        'fa-camera-retro',
        'fa-car',
        'fa-caret-down',
        'fa-caret-left',
        'fa-caret-right',
        'fa-caret-square-o-down',
        'fa-caret-square-o-left',
        'fa-caret-square-o-right',
        'fa-caret-square-o-up',
        'fa-caret-up',
        'fa-cc',
        'fa-cc-amex',
        'fa-cc-discover',
        'fa-cc-mastercard',
        'fa-cc-paypal',
        'fa-cc-stripe',
        'fa-cc-visa',
        'fa-certificate',
        'fa-chain-broken',
        'fa-check',
        'fa-check-circle',
        'fa-check-circle-o',
        'fa-check-square',
        'fa-check-square-o',
        'fa-chevron-circle-down',
        'fa-chevron-circle-left',
        'fa-chevron-circle-right',
        'fa-chevron-circle-up',
        'fa-chevron-down',
        'fa-chevron-left',
        'fa-chevron-right',
        'fa-chevron-up',
        'fa-child',
        'fa-circle',
        'fa-circle-o',
        'fa-circle-o-notch',
        'fa-circle-thin',
        'fa-clipboard',
        'fa-clock-o',
        'fa-cloud',
        'fa-cloud-download',
        'fa-cloud-upload',
        'fa-code',
        'fa-code-fork',
        'fa-codepen',
        'fa-coffee',
        'fa-cog',
        'fa-cogs',
        'fa-columns',
        'fa-comment',
        'fa-comment-o',
        'fa-comments',
        'fa-comments-o',
        'fa-compass',
        'fa-compress',
        'fa-copyright',
        'fa-credit-card',
        'fa-crop',
        'fa-crosshairs',
        'fa-css3',
        'fa-cube',
        'fa-cubes',
        'fa-cutlery',
        'fa-database',
        'fa-delicious',
        'fa-desktop',
        'fa-deviantart',
        'fa-digg',
        'fa-dot-circle-o',
        'fa-download',
        'fa-dribbble',
        'fa-dropbox',
        'fa-drupal',
        'fa-eject',
        'fa-ellipsis-h',
        'fa-ellipsis-v',
        'fa-empire',
        'fa-envelope',
        'fa-envelope-o',
        'fa-envelope-square',
        'fa-eraser',
        'fa-eur',
        'fa-exchange',
        'fa-exclamation',
        'fa-exclamation-circle',
        'fa-exclamation-triangle',
        'fa-expand',
        'fa-external-link',
        'fa-external-link-square',
        'fa-eye',
        'fa-eye-slash',
        'fa-eyedropper',
        'fa-facebook',
        'fa-facebook-square',
        'fa-fast-backward',
        'fa-fast-forward',
        'fa-fax',
        'fa-female',
        'fa-fighter-jet',
        'fa-file',
        'fa-file-archive-o',
        'fa-file-audio-o',
        'fa-file-code-o',
        'fa-file-excel-o',
        'fa-file-image-o',
        'fa-file-o',
        'fa-file-pdf-o',
        'fa-file-powerpoint-o',
        'fa-file-text',
        'fa-file-text-o',
        'fa-file-video-o',
        'fa-file-word-o',
        'fa-files-o',
        'fa-film',
        'fa-filter',
        'fa-fire',
        'fa-fire-extinguisher',
        'fa-flag',
        'fa-flag-checkered',
        'fa-flag-o',
        'fa-flask',
        'fa-flickr',
        'fa-floppy-o',
        'fa-folder',
        'fa-folder-o',
        'fa-folder-open',
        'fa-folder-open-o',
        'fa-font',
        'fa-forward',
        'fa-foursquare',
        'fa-frown-o',
        'fa-futbol-o',
        'fa-gamepad',
        'fa-gavel',
        'fa-gbp',
        'fa-gift',
        'fa-git',
        'fa-git-square',
        'fa-github',
        'fa-github-alt',
        'fa-github-square',
        'fa-gittip',
        'fa-glass',
        'fa-globe',
        'fa-google',
        'fa-google-plus',
        'fa-google-plus-square',
        'fa-google-wallet',
        'fa-graduation-cap',
        'fa-h-square',
        'fa-hacker-news',
        'fa-hand-o-down',
        'fa-hand-o-left',
        'fa-hand-o-right',
        'fa-hand-o-up',
        'fa-hdd-o',
        'fa-header',
        'fa-headphones',
        'fa-heart',
        'fa-heart-o',
        'fa-history',
        'fa-home',
        'fa-hospital-o',
        'fa-html5',
        'fa-ils',
        'fa-inbox',
        'fa-indent',
        'fa-info',
        'fa-info-circle',
        'fa-inr',
        'fa-instagram',
        'fa-ioxhost',
        'fa-italic',
        'fa-joomla',
        'fa-jpy',
        'fa-jsfiddle',
        'fa-key',
        'fa-keyboard-o',
        'fa-krw',
        'fa-language',
        'fa-laptop',
        'fa-lastfm',
        'fa-lastfm-square',
        'fa-leaf',
        'fa-lemon-o',
        'fa-level-down',
        'fa-level-up',
        'fa-life-ring',
        'fa-lightbulb-o',
        'fa-line-chart',
        'fa-link',
        'fa-linkedin',
        'fa-linkedin-square',
        'fa-linux',
        'fa-list',
        'fa-list-alt',
        'fa-list-ol',
        'fa-list-ul',
        'fa-location-arrow',
        'fa-lock',
        'fa-long-arrow-down',
        'fa-long-arrow-left',
        'fa-long-arrow-right',
        'fa-long-arrow-up',
        'fa-magic',
        'fa-magnet',
        'fa-male',
        'fa-map-marker',
        'fa-maxcdn',
        'fa-meanpath',
        'fa-medkit',
        'fa-meh-o',
        'fa-microphone',
        'fa-microphone-slash',
        'fa-minus',
        'fa-minus-circle',
        'fa-minus-square',
        'fa-minus-square-o',
        'fa-mobile',
        'fa-money',
        'fa-moon-o',
        'fa-music',
        'fa-newspaper-o',
        'fa-openid',
        'fa-outdent',
        'fa-pagelines',
        'fa-paint-brush',
        'fa-paper-plane',
        'fa-paper-plane-o',
        'fa-paperclip',
        'fa-paragraph',
        'fa-pause',
        'fa-paw',
        'fa-paypal',
        'fa-pencil',
        'fa-pencil-square',
        'fa-pencil-square-o',
        'fa-phone',
        'fa-phone-square',
        'fa-picture-o',
        'fa-pie-chart',
        'fa-pied-piper',
        'fa-pied-piper-alt',
        'fa-pinterest',
        'fa-pinterest-square',
        'fa-plane',
        'fa-play',
        'fa-play-circle',
        'fa-play-circle-o',
        'fa-plug',
        'fa-plus',
        'fa-plus-circle',
        'fa-plus-square',
        'fa-plus-square-o',
        'fa-power-off',
        'fa-print',
        'fa-puzzle-piece',
        'fa-qq',
        'fa-qrcode',
        'fa-question',
        'fa-question-circle',
        'fa-quote-left',
        'fa-quote-right',
        'fa-random',
        'fa-rebel',
        'fa-recycle',
        'fa-reddit',
        'fa-reddit-square',
        'fa-refresh',
        'fa-renren',
        'fa-repeat',
        'fa-reply',
        'fa-reply-all',
        'fa-retweet',
        'fa-road',
        'fa-rocket',
        'fa-rss',
        'fa-rss-square',
        'fa-rub',
        'fa-scissors',
        'fa-search',
        'fa-search-minus',
        'fa-search-plus',
        'fa-share',
        'fa-share-alt',
        'fa-share-alt-square',
        'fa-share-square',
        'fa-share-square-o',
        'fa-shield',
        'fa-shopping-cart',
        'fa-sign-in',
        'fa-sign-out',
        'fa-signal',
        'fa-sitemap',
        'fa-skype',
        'fa-slack',
        'fa-sliders',
        'fa-slideshare',
        'fa-smile-o',
        'fa-sort',
        'fa-sort-alpha-asc',
        'fa-sort-alpha-desc',
        'fa-sort-amount-asc',
        'fa-sort-amount-desc',
        'fa-sort-asc',
        'fa-sort-desc',
        'fa-sort-numeric-asc',
        'fa-sort-numeric-desc',
        'fa-soundcloud',
        'fa-space-shuttle',
        'fa-spinner',
        'fa-spoon',
        'fa-spotify',
        'fa-square',
        'fa-square-o',
        'fa-stack-exchange',
        'fa-stack-overflow',
        'fa-star',
        'fa-star-half',
        'fa-star-half-o',
        'fa-star-o',
        'fa-steam',
        'fa-steam-square',
        'fa-step-backward',
        'fa-step-forward',
        'fa-stethoscope',
        'fa-stop',
        'fa-strikethrough',
        'fa-stumbleupon',
        'fa-stumbleupon-circle',
        'fa-subscript',
        'fa-suitcase',
        'fa-sun-o',
        'fa-superscript',
        'fa-table',
        'fa-tablet',
        'fa-tachometer',
        'fa-tag',
        'fa-tags',
        'fa-tasks',
        'fa-taxi',
        'fa-tencent-weibo',
        'fa-terminal',
        'fa-text-height',
        'fa-text-width',
        'fa-th',
        'fa-th-large',
        'fa-th-list',
        'fa-thumb-tack',
        'fa-thumbs-down',
        'fa-thumbs-o-down',
        'fa-thumbs-o-up',
        'fa-thumbs-up',
        'fa-ticket',
        'fa-times',
        'fa-times-circle',
        'fa-times-circle-o',
        'fa-tint',
        'fa-toggle-off',
        'fa-toggle-on',
        'fa-trash',
        'fa-trash-o',
        'fa-tree',
        'fa-trello',
        'fa-trophy',
        'fa-truck',
        'fa-try',
        'fa-tty',
        'fa-tumblr',
        'fa-tumblr-square',
        'fa-twitch',
        'fa-twitter',
        'fa-twitter-square',
        'fa-umbrella',
        'fa-underline',
        'fa-undo',
        'fa-university',
        'fa-unlock',
        'fa-unlock-alt',
        'fa-upload',
        'fa-usd',
        'fa-user',
        'fa-user-md',
        'fa-users',
        'fa-video-camera',
        'fa-vimeo-square',
        'fa-vine',
        'fa-vk',
        'fa-volume-down',
        'fa-volume-off',
        'fa-volume-up',
        'fa-weibo',
        'fa-weixin',
        'fa-wheelchair',
        'fa-wifi',
        'fa-windows',
        'fa-wordpress',
        'fa-wrench',
        'fa-xing',
        'fa-xing-square',
        'fa-yahoo',
        'fa-yelp',
        'fa-youtube',
        'fa-youtube-play',
        'fa-youtube-square',
    );


    /**
     * Google icon list 
     * @var array
     */
    protected $google_icons = array(
        "&#xE838;" => "Star",
        "&#xe84d;" => "3d Rotation",
        "&#xeb3b;" => "Ac Unit",
        "&#xe190;" => "Access Alarm",
        "&#xe191;" => "Access Alarms",
        "&#xe192;" => "Access Time",
        "&#xe84e;" => "Accessibility",
        "&#xe914;" => "Accessible",
        "&#xe84f;" => "Account Balance",
        "&#xe850;" => "Account Balance Wallet",
        "&#xe851;" => "Account Box",
        "&#xe853;" => "Account Circle",
        "&#xe60e;" => "Adb",
        "&#xe145;" => "Add",
        "&#xe439;" => "Add A Photo",
        "&#xe193;" => "Add Alarm",
        "&#xe003;" => "Add Alert",
        "&#xe146;" => "Add Box",
        "&#xe147;" => "Add Circle",
        "&#xe148;" => "Add Circle Outline",
        "&#xe567;" => "Add Location",
        "&#xe854;" => "Add Shopping Cart",
        "&#xe39d;" => "Add To Photos",
        "&#xe05c;" => "Add To Queue",
        "&#xe39e;" => "Adjust",
        "&#xe630;" => "Airline Seat Flat",
        "&#xe631;" => "Airline Seat Flat Angled",
        "&#xe632;" => "Airline Seat Individual Suite",
        "&#xe633;" => "Airline Seat Legroom Extra",
        "&#xe634;" => "Airline Seat Legroom Normal",
        "&#xe635;" => "Airline Seat Legroom Reduced",
        "&#xe636;" => "Airline Seat Recline Extra",
        "&#xe637;" => "Airline Seat Recline Normal",
        "&#xe195;" => "Airplanemode Active",
        "&#xe194;" => "Airplanemode Inactive",
        "&#xe055;" => "Airplay",
        "&#xeb3c;" => "Airport Shuttle",
        "&#xe855;" => "Alarm",
        "&#xe856;" => "Alarm Add",
        "&#xe857;" => "Alarm Off",
        "&#xe858;" => "Alarm On",
        "&#xe019;" => "Album",
        "&#xeb3d;" => "All Inclusive",
        "&#xe90b;" => "All Out",
        "&#xe859;" => "Android",
        "&#xe85a;" => "Announcement",
        "&#xe5c3;" => "Apps",
        "&#xe149;" => "Archive",
        "&#xe5c4;" => "Arrow Back",
        "&#xe5db;" => "Arrow Downward",
        "&#xe5c5;" => "Arrow Drop Down",
        "&#xe5c6;" => "Arrow Drop Down Circle",
        "&#xe5c7;" => "Arrow Drop Up",
        "&#xe5c8;" => "Arrow Forward",
        "&#xe5d8;" => "Arrow Upward",
        "&#xe060;" => "Art Track",
        "&#xe85b;" => "Aspect Ratio",
        "&#xe85c;" => "Assessment",
        "&#xe85d;" => "Assignment",
        "&#xe85e;" => "Assignment Ind",
        "&#xe85f;" => "Assignment Late",
        "&#xe860;" => "Assignment Return",
        "&#xe861;" => "Assignment Returned",
        "&#xe862;" => "Assignment Turned In",
        "&#xe39f;" => "Assistant",
        "&#xe3a0;" => "Assistant Photo",
        "&#xe226;" => "Attach File",
        "&#xe227;" => "Attach Money",
        "&#xe2bc;" => "Attachment",
        "&#xe3a1;" => "Audiotrack",
        "&#xe863;" => "Autorenew",
        "&#xe01b;" => "Av Timer",
        "&#xe14a;" => "Backspace",
        "&#xe864;" => "Backup",
        "&#xe19c;" => "Battery Alert",
        "&#xe1a3;" => "Battery Charging Full",
        "&#xe1a4;" => "Battery Full",
        "&#xe1a5;" => "Battery Std",
        "&#xe1a6;" => "Battery Unknown",
        "&#xeb3e;" => "Beach Access",
        "&#xe52d;" => "Beenhere",
        "&#xe14b;" => "Block",
        "&#xe1a7;" => "Bluetooth",
        "&#xe60f;" => "Bluetooth Audio",
        "&#xe1a8;" => "Bluetooth Connected",
        "&#xe1a9;" => "Bluetooth Disabled",
        "&#xe1aa;" => "Bluetooth Searching",
        "&#xe3a2;" => "Blur Circular",
        "&#xe3a3;" => "Blur Linear",
        "&#xe3a4;" => "Blur Off",
        "&#xe3a5;" => "Blur On",
        "&#xe865;" => "Book",
        "&#xe866;" => "Bookmark",
        "&#xe867;" => "Bookmark Border",
        "&#xe228;" => "Border All",
        "&#xe229;" => "Border Bottom",
        "&#xe22a;" => "Border Clear",
        "&#xe22b;" => "Border Color",
        "&#xe22c;" => "Border Horizontal",
        "&#xe22d;" => "Border Inner",
        "&#xe22e;" => "Border Left",
        "&#xe22f;" => "Border Outer",
        "&#xe230;" => "Border Right",
        "&#xe231;" => "Border Style",
        "&#xe232;" => "Border Top",
        "&#xe233;" => "Border Vertical",
        "&#xe06b;" => "Branding Watermark",
        "&#xe3a6;" => "Brightness 1",
        "&#xe3a7;" => "Brightness 2",
        "&#xe3a8;" => "Brightness 3",
        "&#xe3a9;" => "Brightness 4",
        "&#xe3aa;" => "Brightness 5",
        "&#xe3ab;" => "Brightness 6",
        "&#xe3ac;" => "Brightness 7",
        "&#xe1ab;" => "Brightness Auto",
        "&#xe1ac;" => "Brightness High",
        "&#xe1ad;" => "Brightness Low",
        "&#xe1ae;" => "Brightness Medium",
        "&#xe3ad;" => "Broken Image",
        "&#xe3ae;" => "Brush",
        "&#xe6dd;" => "Bubble Chart",
        "&#xe868;" => "Bug Report",
        "&#xe869;" => "Build",
        "&#xe43c;" => "Burst Mode",
        "&#xe0af;" => "Business",
        "&#xeb3f;" => "Business Center",
        "&#xe86a;" => "Cached",
        "&#xe7e9;" => "Cake",
        "&#xe0b0;" => "Call",
        "&#xe0b1;" => "Call End",
        "&#xe0b2;" => "Call Made",
        "&#xe0b3;" => "Call Merge",
        "&#xe0b4;" => "Call Missed",
        "&#xe0e4;" => "Call Missed Outgoing",
        "&#xe0b5;" => "Call Received",
        "&#xe0b6;" => "Call Split",
        "&#xe06c;" => "Call To Action",
        "&#xe3af;" => "Camera",
        "&#xe3b0;" => "Camera Alt",
        "&#xe8fc;" => "Camera Enhance",
        "&#xe3b1;" => "Camera Front",
        "&#xe3b2;" => "Camera Rear",
        "&#xe3b3;" => "Camera Roll",
        "&#xe5c9;" => "Cancel",
        "&#xe8f6;" => "Card Giftcard",
        "&#xe8f7;" => "Card Membership",
        "&#xe8f8;" => "Card Travel",
        "&#xeb40;" => "Casino",
        "&#xe307;" => "Cast",
        "&#xe308;" => "Cast Connected",
        "&#xe3b4;" => "Center Focus Strong",
        "&#xe3b5;" => "Center Focus Weak",
        "&#xe86b;" => "Change History",
        "&#xe0b7;" => "Chat",
        "&#xe0ca;" => "Chat Bubble",
        "&#xe0cb;" => "Chat Bubble Outline",
        "&#xe5ca;" => "Check",
        "&#xe834;" => "Check Box",
        "&#xe835;" => "Check Box Outline Blank",
        "&#xe86c;" => "Check Circle",
        "&#xe5cb;" => "Chevron Left",
        "&#xe5cc;" => "Chevron Right",
        "&#xeb41;" => "Child Care",
        "&#xeb42;" => "Child Friendly",
        "&#xe86d;" => "Chrome Reader Mode",
        "&#xe86e;" => "Class",
        "&#xe14c;" => "Clear",
        "&#xe0b8;" => "Clear All",
        "&#xe5cd;" => "Close",
        "&#xe01c;" => "Closed Caption",
        "&#xe2bd;" => "Cloud",
        "&#xe2be;" => "Cloud Circle",
        "&#xe2bf;" => "Cloud Done",
        "&#xe2c0;" => "Cloud Download",
        "&#xe2c1;" => "Cloud Off",
        "&#xe2c2;" => "Cloud Queue",
        "&#xe2c3;" => "Cloud Upload",
        "&#xe86f;" => "Code",
        "&#xe3b6;" => "Collections",
        "&#xe431;" => "Collections Bookmark",
        "&#xe3b7;" => "Color Lens",
        "&#xe3b8;" => "Colorize",
        "&#xe0b9;" => "Comment",
        "&#xe3b9;" => "Compare",
        "&#xe915;" => "Compare Arrows",
        "&#xe30a;" => "Computer",
        "&#xe638;" => "Confirmation Number",
        "&#xe0d0;" => "Contact Mail",
        "&#xe0cf;" => "Contact Phone",
        "&#xe0ba;" => "Contacts",
        "&#xe14d;" => "Content Copy",
        "&#xe14e;" => "Content Cut",
        "&#xe14f;" => "Content Paste",
        "&#xe3ba;" => "Control Point",
        "&#xe3bb;" => "Control Point Duplicate",
        "&#xe90c;" => "Copyright",
        "&#xe150;" => "Create",
        "&#xe2cc;" => "Create New Folder",
        "&#xe870;" => "Credit Card",
        "&#xe3be;" => "Crop",
        "&#xe3bc;" => "Crop 16 9",
        "&#xe3bd;" => "Crop 3 2",
        "&#xe3bf;" => "Crop 5 4",
        "&#xe3c0;" => "Crop 7 5",
        "&#xe3c1;" => "Crop Din",
        "&#xe3c2;" => "Crop Free",
        "&#xe3c3;" => "Crop Landscape",
        "&#xe3c4;" => "Crop Original",
        "&#xe3c5;" => "Crop Portrait",
        "&#xe437;" => "Crop Rotate",
        "&#xe3c6;" => "Crop Square",
        "&#xe871;" => "Dashboard",
        "&#xe1af;" => "Data Usage",
        "&#xe916;" => "Date Range",
        "&#xe3c7;" => "Dehaze",
        "&#xe872;" => "Delete",
        "&#xe92b;" => "Delete Forever",
        "&#xe16c;" => "Delete Sweep",
        "&#xe873;" => "Description",
        "&#xe30b;" => "Desktop Mac",
        "&#xe30c;" => "Desktop Windows",
        "&#xe3c8;" => "Details",
        "&#xe30d;" => "Developer Board",
        "&#xe1b0;" => "Developer Mode",
        "&#xe335;" => "Device Hub",
        "&#xe1b1;" => "Devices",
        "&#xe337;" => "Devices Other",
        "&#xe0bb;" => "Dialer Sip",
        "&#xe0bc;" => "Dialpad",
        "&#xe52e;" => "Directions",
        "&#xe52f;" => "Directions Bike",
        "&#xe532;" => "Directions Boat",
        "&#xe530;" => "Directions Bus",
        "&#xe531;" => "Directions Car",
        "&#xe534;" => "Directions Railway",
        "&#xe566;" => "Directions Run",
        "&#xe533;" => "Directions Subway",
        "&#xe535;" => "Directions Transit",
        "&#xe536;" => "Directions Walk",
        "&#xe610;" => "Disc Full",
        "&#xe875;" => "Dns",
        "&#xe612;" => "Do Not Disturb",
        "&#xe611;" => "Do Not Disturb Alt",
        "&#xe643;" => "Do Not Disturb Off",
        "&#xe644;" => "Do Not Disturb On",
        "&#xe30e;" => "Dock",
        "&#xe7ee;" => "Domain",
        "&#xe876;" => "Done",
        "&#xe877;" => "Done All",
        "&#xe917;" => "Donut Large",
        "&#xe918;" => "Donut Small",
        "&#xe151;" => "Drafts",
        "&#xe25d;" => "Drag Handle",
        "&#xe613;" => "Drive Eta",
        "&#xe1b2;" => "Dvr",
        "&#xe3c9;" => "Edit",
        "&#xe568;" => "Edit Location",
        "&#xe8fb;" => "Eject",
        "&#xe0be;" => "Email",
        "&#xe63f;" => "Enhanced Encryption",
        "&#xe01d;" => "Equalizer",
        "&#xe000;" => "Error",
        "&#xe001;" => "Error Outline",
        "&#xe926;" => "Euro Symbol",
        "&#xe56d;" => "Ev Station",
        "&#xe878;" => "Event",
        "&#xe614;" => "Event Available",
        "&#xe615;" => "Event Busy",
        "&#xe616;" => "Event Note",
        "&#xe903;" => "Event Seat",
        "&#xe879;" => "Exit To App",
        "&#xe5ce;" => "Expand Less",
        "&#xe5cf;" => "Expand More",
        "&#xe01e;" => "Explicit",
        "&#xe87a;" => "Explore",
        "&#xe3ca;" => "Exposure",
        "&#xe3cb;" => "Exposure Neg 1",
        "&#xe3cc;" => "Exposure Neg 2",
        "&#xe3cd;" => "Exposure Plus 1",
        "&#xe3ce;" => "Exposure Plus 2",
        "&#xe3cf;" => "Exposure Zero",
        "&#xe87b;" => "Extension",
        "&#xe87c;" => "Face",
        "&#xe01f;" => "Fast Forward",
        "&#xe020;" => "Fast Rewind",
        "&#xe87d;" => "Favorite",
        "&#xe87e;" => "Favorite Border",
        "&#xe06d;" => "Featured Play List",
        "&#xe06e;" => "Featured Video",
        "&#xe87f;" => "Feedback",
        "&#xe05d;" => "Fiber Dvr",
        "&#xe061;" => "Fiber Manual Record",
        "&#xe05e;" => "Fiber New",
        "&#xe06a;" => "Fiber Pin",
        "&#xe062;" => "Fiber Smart Record",
        "&#xe2c4;" => "File Download",
        "&#xe2c6;" => "File Upload",
        "&#xe3d3;" => "Filter",
        "&#xe3d0;" => "Filter 1",
        "&#xe3d1;" => "Filter 2",
        "&#xe3d2;" => "Filter 3",
        "&#xe3d4;" => "Filter 4",
        "&#xe3d5;" => "Filter 5",
        "&#xe3d6;" => "Filter 6",
        "&#xe3d7;" => "Filter 7",
        "&#xe3d8;" => "Filter 8",
        "&#xe3d9;" => "Filter 9",
        "&#xe3da;" => "Filter 9 Plus",
        "&#xe3db;" => "Filter B And W",
        "&#xe3dc;" => "Filter Center Focus",
        "&#xe3dd;" => "Filter Drama",
        "&#xe3de;" => "Filter Frames",
        "&#xe3df;" => "Filter Hdr",
        "&#xe152;" => "Filter List",
        "&#xe3e0;" => "Filter None",
        "&#xe3e2;" => "Filter Tilt Shift",
        "&#xe3e3;" => "Filter Vintage",
        "&#xe880;" => "Find In Page",
        "&#xe881;" => "Find Replace",
        "&#xe90d;" => "Fingerprint",
        "&#xe5dc;" => "First Page",
        "&#xeb43;" => "Fitness Center",
        "&#xe153;" => "Flag",
        "&#xe3e4;" => "Flare",
        "&#xe3e5;" => "Flash Auto",
        "&#xe3e6;" => "Flash Off",
        "&#xe3e7;" => "Flash On",
        "&#xe539;" => "Flight",
        "&#xe904;" => "Flight Land",
        "&#xe905;" => "Flight Takeoff",
        "&#xe3e8;" => "Flip",
        "&#xe882;" => "Flip To Back",
        "&#xe883;" => "Flip To Front",
        "&#xe2c7;" => "Folder",
        "&#xe2c8;" => "Folder Open",
        "&#xe2c9;" => "Folder Shared",
        "&#xe617;" => "Folder Special",
        "&#xe167;" => "Font Download",
        "&#xe234;" => "Format Align Center",
        "&#xe235;" => "Format Align Justify",
        "&#xe236;" => "Format Align Left",
        "&#xe237;" => "Format Align Right",
        "&#xe238;" => "Format Bold",
        "&#xe239;" => "Format Clear",
        "&#xe23a;" => "Format Color Fill",
        "&#xe23b;" => "Format Color Reset",
        "&#xe23c;" => "Format Color Text",
        "&#xe23d;" => "Format Indent Decrease",
        "&#xe23e;" => "Format Indent Increase",
        "&#xe23f;" => "Format Italic",
        "&#xe240;" => "Format Line Spacing",
        "&#xe241;" => "Format List Bulleted",
        "&#xe242;" => "Format List Numbered",
        "&#xe243;" => "Format Paint",
        "&#xe244;" => "Format Quote",
        "&#xe25e;" => "Format Shapes",
        "&#xe245;" => "Format Size",
        "&#xe246;" => "Format Strikethrough",
        "&#xe247;" => "Format Textdirection L To R",
        "&#xe248;" => "Format Textdirection R To L",
        "&#xe249;" => "Format Underlined",
        "&#xe0bf;" => "Forum",
        "&#xe154;" => "Forward",
        "&#xe056;" => "Forward 10",
        "&#xe057;" => "Forward 30",
        "&#xe058;" => "Forward 5",
        "&#xeb44;" => "Free Breakfast",
        "&#xe5d0;" => "Fullscreen",
        "&#xe5d1;" => "Fullscreen Exit",
        "&#xe24a;" => "Functions",
        "&#xe927;" => "G Translate",
        "&#xe30f;" => "Gamepad",
        "&#xe021;" => "Games",
        "&#xe90e;" => "Gavel",
        "&#xe155;" => "Gesture",
        "&#xe884;" => "Get App",
        "&#xe908;" => "Gif",
        "&#xeb45;" => "Golf Course",
        "&#xe1b3;" => "Gps Fixed",
        "&#xe1b4;" => "Gps Not Fixed",
        "&#xe1b5;" => "Gps Off",
        "&#xe885;" => "Grade",
        "&#xe3e9;" => "Gradient",
        "&#xe3ea;" => "Grain",
        "&#xe1b8;" => "Graphic Eq",
        "&#xe3eb;" => "Grid Off",
        "&#xe3ec;" => "Grid On",
        "&#xe7ef;" => "Group",
        "&#xe7f0;" => "Group Add",
        "&#xe886;" => "Group Work",
        "&#xe052;" => "Hd",
        "&#xe3ed;" => "Hdr Off",
        "&#xe3ee;" => "Hdr On",
        "&#xe3f1;" => "Hdr Strong",
        "&#xe3f2;" => "Hdr Weak",
        "&#xe310;" => "Headset",
        "&#xe311;" => "Headset Mic",
        "&#xe3f3;" => "Healing",
        "&#xe023;" => "Hearing",
        "&#xe887;" => "Help",
        "&#xe8fd;" => "Help Outline",
        "&#xe024;" => "High Quality",
        "&#xe25f;" => "Highlight",
        "&#xe888;" => "Highlight Off",
        "&#xe889;" => "History",
        "&#xe88a;" => "Home",
        "&#xeb46;" => "Hot Tub",
        "&#xe53a;" => "Hotel",
        "&#xe88b;" => "Hourglass Empty",
        "&#xe88c;" => "Hourglass Full",
        "&#xe902;" => "Http",
        "&#xe88d;" => "Https",
        "&#xe3f4;" => "Image",
        "&#xe3f5;" => "Image Aspect Ratio",
        "&#xe0e0;" => "Import Contacts",
        "&#xe0c3;" => "Import Export",
        "&#xe912;" => "Important Devices",
        "&#xe156;" => "Inbox",
        "&#xe909;" => "Indeterminate Check Box",
        "&#xe88e;" => "Info",
        "&#xe88f;" => "Info Outline",
        "&#xe890;" => "Input",
        "&#xe24b;" => "Insert Chart",
        "&#xe24c;" => "Insert Comment",
        "&#xe24d;" => "Insert Drive File",
        "&#xe24e;" => "Insert Emoticon",
        "&#xe24f;" => "Insert Invitation",
        "&#xe250;" => "Insert Link",
        "&#xe251;" => "Insert Photo",
        "&#xe891;" => "Invert Colors",
        "&#xe0c4;" => "Invert Colors Off",
        "&#xe3f6;" => "Iso",
        "&#xe312;" => "Keyboard",
        "&#xe313;" => "Keyboard Arrow Down",
        "&#xe314;" => "Keyboard Arrow Left",
        "&#xe315;" => "Keyboard Arrow Right",
        "&#xe316;" => "Keyboard Arrow Up",
        "&#xe317;" => "Keyboard Backspace",
        "&#xe318;" => "Keyboard Capslock",
        "&#xe31a;" => "Keyboard Hide",
        "&#xe31b;" => "Keyboard Return",
        "&#xe31c;" => "Keyboard Tab",
        "&#xe31d;" => "Keyboard Voice",
        "&#xeb47;" => "Kitchen",
        "&#xe892;" => "Label",
        "&#xe893;" => "Label Outline",
        "&#xe3f7;" => "Landscape",
        "&#xe894;" => "Language",
        "&#xe31e;" => "Laptop",
        "&#xe31f;" => "Laptop Chromebook",
        "&#xe320;" => "Laptop Mac",
        "&#xe321;" => "Laptop Windows",
        "&#xe5dd;" => "Last Page",
        "&#xe895;" => "Launch",
        "&#xe53b;" => "Layers",
        "&#xe53c;" => "Layers Clear",
        "&#xe3f8;" => "Leak Add",
        "&#xe3f9;" => "Leak Remove",
        "&#xe3fa;" => "Lens",
        "&#xe02e;" => "Library Add",
        "&#xe02f;" => "Library Books",
        "&#xe030;" => "Library Music",
        "&#xe90f;" => "Lightbulb Outline",
        "&#xe919;" => "Line Style",
        "&#xe91a;" => "Line Weight",
        "&#xe260;" => "Linear Scale",
        "&#xe157;" => "Link",
        "&#xe438;" => "Linked Camera",
        "&#xe896;" => "List",
        "&#xe0c6;" => "Live Help",
        "&#xe639;" => "Live Tv",
        "&#xe53f;" => "Local Activity",
        "&#xe53d;" => "Local Airport",
        "&#xe53e;" => "Local Atm",
        "&#xe540;" => "Local Bar",
        "&#xe541;" => "Local Cafe",
        "&#xe542;" => "Local Car Wash",
        "&#xe543;" => "Local Convenience Store",
        "&#xe556;" => "Local Dining",
        "&#xe544;" => "Local Drink",
        "&#xe545;" => "Local Florist",
        "&#xe546;" => "Local Gas Station",
        "&#xe547;" => "Local Grocery Store",
        "&#xe548;" => "Local Hospital",
        "&#xe549;" => "Local Hotel",
        "&#xe54a;" => "Local Laundry Service",
        "&#xe54b;" => "Local Library",
        "&#xe54c;" => "Local Mall",
        "&#xe54d;" => "Local Movies",
        "&#xe54e;" => "Local Offer",
        "&#xe54f;" => "Local Parking",
        "&#xe550;" => "Local Pharmacy",
        "&#xe551;" => "Local Phone",
        "&#xe552;" => "Local Pizza",
        "&#xe553;" => "Local Play",
        "&#xe554;" => "Local Post Office",
        "&#xe555;" => "Local Printshop",
        "&#xe557;" => "Local See",
        "&#xe558;" => "Local Shipping",
        "&#xe559;" => "Local Taxi",
        "&#xe7f1;" => "Location City",
        "&#xe1b6;" => "Location Disabled",
        "&#xe0c7;" => "Location Off",
        "&#xe0c8;" => "Location On",
        "&#xe1b7;" => "Location Searching",
        "&#xe897;" => "Lock",
        "&#xe898;" => "Lock Open",
        "&#xe899;" => "Lock Outline",
        "&#xe3fc;" => "Looks",
        "&#xe3fb;" => "Looks 3",
        "&#xe3fd;" => "Looks 4",
        "&#xe3fe;" => "Looks 5",
        "&#xe3ff;" => "Looks 6",
        "&#xe400;" => "Looks One",
        "&#xe401;" => "Looks Two",
        "&#xe028;" => "Loop",
        "&#xe402;" => "Loupe",
        "&#xe16d;" => "Low Priority",
        "&#xe89a;" => "Loyalty",
        "&#xe158;" => "Mail",
        "&#xe0e1;" => "Mail Outline",
        "&#xe55b;" => "Map",
        "&#xe159;" => "Markunread",
        "&#xe89b;" => "Markunread Mailbox",
        "&#xe322;" => "Memory",
        "&#xe5d2;" => "Menu",
        "&#xe252;" => "Merge Type",
        "&#xe0c9;" => "Message",
        "&#xe029;" => "Mic",
        "&#xe02a;" => "Mic None",
        "&#xe02b;" => "Mic Off",
        "&#xe618;" => "Mms",
        "&#xe253;" => "Mode Comment",
        "&#xe254;" => "Mode Edit",
        "&#xe263;" => "Monetization On",
        "&#xe25c;" => "Money Off",
        "&#xe403;" => "Monochrome Photos",
        "&#xe7f2;" => "Mood",
        "&#xe7f3;" => "Mood Bad",
        "&#xe619;" => "More",
        "&#xe5d3;" => "More Horiz",
        "&#xe5d4;" => "More Vert",
        "&#xe91b;" => "Motorcycle",
        "&#xe323;" => "Mouse",
        "&#xe168;" => "Move To Inbox",
        "&#xe02c;" => "Movie",
        "&#xe404;" => "Movie Creation",
        "&#xe43a;" => "Movie Filter",
        "&#xe6df;" => "Multiline Chart",
        "&#xe405;" => "Music Note",
        "&#xe063;" => "Music Video",
        "&#xe55c;" => "My Location",
        "&#xe406;" => "Nature",
        "&#xe407;" => "Nature People",
        "&#xe408;" => "Navigate Before",
        "&#xe409;" => "Navigate Next",
        "&#xe55d;" => "Navigation",
        "&#xe569;" => "Near Me",
        "&#xe1b9;" => "Network Cell",
        "&#xe640;" => "Network Check",
        "&#xe61a;" => "Network Locked",
        "&#xe1ba;" => "Network Wifi",
        "&#xe031;" => "New Releases",
        "&#xe16a;" => "Next Week",
        "&#xe1bb;" => "Nfc",
        "&#xe641;" => "No Encryption",
        "&#xe0cc;" => "No Sim",
        "&#xe033;" => "Not Interested",
        "&#xe06f;" => "Note",
        "&#xe89c;" => "Note Add",
        "&#xe7f4;" => "Notifications",
        "&#xe7f7;" => "Notifications Active",
        "&#xe7f5;" => "Notifications None",
        "&#xe7f6;" => "Notifications Off",
        "&#xe7f8;" => "Notifications Paused",
        "&#xe90a;" => "Offline Pin",
        "&#xe63a;" => "Ondemand Video",
        "&#xe91c;" => "Opacity",
        "&#xe89d;" => "Open In Browser",
        "&#xe89e;" => "Open In New",
        "&#xe89f;" => "Open With",
        "&#xe7f9;" => "Pages",
        "&#xe8a0;" => "Pageview",
        "&#xe40a;" => "Palette",
        "&#xe925;" => "Pan Tool",
        "&#xe40b;" => "Panorama",
        "&#xe40c;" => "Panorama Fish Eye",
        "&#xe40d;" => "Panorama Horizontal",
        "&#xe40e;" => "Panorama Vertical",
        "&#xe40f;" => "Panorama Wide Angle",
        "&#xe7fa;" => "Party Mode",
        "&#xe034;" => "Pause",
        "&#xe035;" => "Pause Circle Filled",
        "&#xe036;" => "Pause Circle Outline",
        "&#xe8a1;" => "Payment",
        "&#xe7fb;" => "People",
        "&#xe7fc;" => "People Outline",
        "&#xe8a2;" => "Perm Camera Mic",
        "&#xe8a3;" => "Perm Contact Calendar",
        "&#xe8a4;" => "Perm Data Setting",
        "&#xe8a5;" => "Perm Device Information",
        "&#xe8a6;" => "Perm Identity",
        "&#xe8a7;" => "Perm Media",
        "&#xe8a8;" => "Perm Phone Msg",
        "&#xe8a9;" => "Perm Scan Wifi",
        "&#xe7fd;" => "Person",
        "&#xe7fe;" => "Person Add",
        "&#xe7ff;" => "Person Outline",
        "&#xe55a;" => "Person Pin",
        "&#xe56a;" => "Person Pin Circle",
        "&#xe63b;" => "Personal Video",
        "&#xe91d;" => "Pets",
        "&#xe0cd;" => "Phone",
        "&#xe324;" => "Phone Android",
        "&#xe61b;" => "Phone Bluetooth Speaker",
        "&#xe61c;" => "Phone Forwarded",
        "&#xe61d;" => "Phone In Talk",
        "&#xe325;" => "Phone Iphone",
        "&#xe61e;" => "Phone Locked",
        "&#xe61f;" => "Phone Missed",
        "&#xe620;" => "Phone Paused",
        "&#xe326;" => "Phonelink",
        "&#xe0db;" => "Phonelink Erase",
        "&#xe0dc;" => "Phonelink Lock",
        "&#xe327;" => "Phonelink Off",
        "&#xe0dd;" => "Phonelink Ring",
        "&#xe0de;" => "Phonelink Setup",
        "&#xe410;" => "Photo",
        "&#xe411;" => "Photo Album",
        "&#xe412;" => "Photo Camera",
        "&#xe43b;" => "Photo Filter",
        "&#xe413;" => "Photo Library",
        "&#xe432;" => "Photo Size Select Actual",
        "&#xe433;" => "Photo Size Select Large",
        "&#xe434;" => "Photo Size Select Small",
        "&#xe415;" => "Picture As Pdf",
        "&#xe8aa;" => "Picture In Picture",
        "&#xe911;" => "Picture In Picture Alt",
        "&#xe6c4;" => "Pie Chart",
        "&#xe6c5;" => "Pie Chart Outlined",
        "&#xe55e;" => "Pin Drop",
        "&#xe55f;" => "Place",
        "&#xe037;" => "Play Arrow",
        "&#xe038;" => "Play Circle Filled",
        "&#xe039;" => "Play Circle Outline",
        "&#xe906;" => "Play For Work",
        "&#xe03b;" => "Playlist Add",
        "&#xe065;" => "Playlist Add Check",
        "&#xe05f;" => "Playlist Play",
        "&#xe800;" => "Plus One",
        "&#xe801;" => "Poll",
        "&#xe8ab;" => "Polymer",
        "&#xeb48;" => "Pool",
        "&#xe0ce;" => "Portable Wifi Off",
        "&#xe416;" => "Portrait",
        "&#xe63c;" => "Power",
        "&#xe336;" => "Power Input",
        "&#xe8ac;" => "Power Settings New",
        "&#xe91e;" => "Pregnant Woman",
        "&#xe0df;" => "Present To All",
        "&#xe8ad;" => "Print",
        "&#xe645;" => "Priority High",
        "&#xe80b;" => "Public",
        "&#xe255;" => "Publish",
        "&#xe8ae;" => "Query Builder",
        "&#xe8af;" => "Question Answer",
        "&#xe03c;" => "Queue",
        "&#xe03d;" => "Queue Music",
        "&#xe066;" => "Queue Play Next",
        "&#xe03e;" => "Radio",
        "&#xe837;" => "Radio Button Checked",
        "&#xe836;" => "Radio Button Unchecked",
        "&#xe560;" => "Rate Review",
        "&#xe8b0;" => "Receipt",
        "&#xe03f;" => "Recent Actors",
        "&#xe91f;" => "Record Voice Over",
        "&#xe8b1;" => "Redeem",
        "&#xe15a;" => "Redo",
        "&#xe5d5;" => "Refresh",
        "&#xe15b;" => "Remove",
        "&#xe15c;" => "Remove Circle",
        "&#xe15d;" => "Remove Circle Outline",
        "&#xe067;" => "Remove From Queue",
        "&#xe417;" => "Remove Red Eye",
        "&#xe928;" => "Remove Shopping Cart",
        "&#xe8fe;" => "Reorder",
        "&#xe040;" => "Repeat",
        "&#xe041;" => "Repeat One",
        "&#xe042;" => "Replay",
        "&#xe059;" => "Replay 10",
        "&#xe05a;" => "Replay 30",
        "&#xe05b;" => "Replay 5",
        "&#xe15e;" => "Reply",
        "&#xe15f;" => "Reply All",
        "&#xe160;" => "Report",
        "&#xe8b2;" => "Report Problem",
        "&#xe56c;" => "Restaurant",
        "&#xe561;" => "Restaurant Menu",
        "&#xe8b3;" => "Restore",
        "&#xe929;" => "Restore Page",
        "&#xe0d1;" => "Ring Volume",
        "&#xe8b4;" => "Room",
        "&#xeb49;" => "Room Service",
        "&#xe418;" => "Rotate 90 Degrees Ccw",
        "&#xe419;" => "Rotate Left",
        "&#xe41a;" => "Rotate Right",
        "&#xe920;" => "Rounded Corner",
        "&#xe328;" => "Router",
        "&#xe921;" => "Rowing",
        "&#xe0e5;" => "Rss Feed",
        "&#xe642;" => "Rv Hookup",
        "&#xe562;" => "Satellite",
        "&#xe161;" => "Save",
        "&#xe329;" => "Scanner",
        "&#xe8b5;" => "Schedule",
        "&#xe80c;" => "School",
        "&#xe1be;" => "Screen Lock Landscape",
        "&#xe1bf;" => "Screen Lock Portrait",
        "&#xe1c0;" => "Screen Lock Rotation",
        "&#xe1c1;" => "Screen Rotation",
        "&#xe0e2;" => "Screen Share",
        "&#xe623;" => "Sd Card",
        "&#xe1c2;" => "Sd Storage",
        "&#xe8b6;" => "Search",
        "&#xe32a;" => "Security",
        "&#xe162;" => "Select All",
        "&#xe163;" => "Send",
        "&#xe811;" => "Sentiment Dissatisfied",
        "&#xe812;" => "Sentiment Neutral",
        "&#xe813;" => "Sentiment Satisfied",
        "&#xe814;" => "Sentiment Very Dissatisfied",
        "&#xe815;" => "Sentiment Very Satisfied",
        "&#xe8b8;" => "Settings",
        "&#xe8b9;" => "Settings Applications",
        "&#xe8ba;" => "Settings Backup Restore",
        "&#xe8bb;" => "Settings Bluetooth",
        "&#xe8bd;" => "Settings Brightness",
        "&#xe8bc;" => "Settings Cell",
        "&#xe8be;" => "Settings Ethernet",
        "&#xe8bf;" => "Settings Input Antenna",
        "&#xe8c0;" => "Settings Input Component",
        "&#xe8c1;" => "Settings Input Composite",
        "&#xe8c2;" => "Settings Input Hdmi",
        "&#xe8c3;" => "Settings Input Svideo",
        "&#xe8c4;" => "Settings Overscan",
        "&#xe8c5;" => "Settings Phone",
        "&#xe8c6;" => "Settings Power",
        "&#xe8c7;" => "Settings Remote",
        "&#xe1c3;" => "Settings System Daydream",
        "&#xe8c8;" => "Settings Voice",
        "&#xe80d;" => "Share",
        "&#xe8c9;" => "Shop",
        "&#xe8ca;" => "Shop Two",
        "&#xe8cb;" => "Shopping Basket",
        "&#xe8cc;" => "Shopping Cart",
        "&#xe261;" => "Short Text",
        "&#xe6e1;" => "Show Chart",
        "&#xe043;" => "Shuffle",
        "&#xe1c8;" => "Signal Cellular 4 Bar",
        "&#xe1cd;" => "Signal Cellular Connected No Internet 4 Bar",
        "&#xe1ce;" => "Signal Cellular No Sim",
        "&#xe1cf;" => "Signal Cellular Null",
        "&#xe1d0;" => "Signal Cellular Off",
        "&#xe1d8;" => "Signal Wifi 4 Bar",
        "&#xe1d9;" => "Signal Wifi 4 Bar Lock",
        "&#xe1da;" => "Signal Wifi Off",
        "&#xe32b;" => "Sim Card",
        "&#xe624;" => "Sim Card Alert",
        "&#xe044;" => "Skip Next",
        "&#xe045;" => "Skip Previous",
        "&#xe41b;" => "Slideshow",
        "&#xe068;" => "Slow Motion Video",
        "&#xe32c;" => "Smartphone",
        "&#xeb4a;" => "Smoke Free",
        "&#xeb4b;" => "Smoking Rooms",
        "&#xe625;" => "Sms",
        "&#xe626;" => "Sms Failed",
        "&#xe046;" => "Snooze",
        "&#xe164;" => "Sort",
        "&#xe053;" => "Sort By Alpha",
        "&#xeb4c;" => "Spa",
        "&#xe256;" => "Space Bar",
        "&#xe32d;" => "Speaker",
        "&#xe32e;" => "Speaker Group",
        "&#xe8cd;" => "Speaker Notes",
        "&#xe92a;" => "Speaker Notes Off",
        "&#xe0d2;" => "Speaker Phone",
        "&#xe8ce;" => "Spellcheck",
        "&#xe83a;" => "Star Border",
        "&#xe839;" => "Star Half",
        "&#xe8d0;" => "Stars",
        "&#xe0d3;" => "Stay Current Landscape",
        "&#xe0d4;" => "Stay Current Portrait",
        "&#xe0d5;" => "Stay Primary Landscape",
        "&#xe0d6;" => "Stay Primary Portrait",
        "&#xe047;" => "Stop",
        "&#xe0e3;" => "Stop Screen Share",
        "&#xe1db;" => "Storage",
        "&#xe8d1;" => "Store",
        "&#xe563;" => "Store Mall Directory",
        "&#xe41c;" => "Straighten",
        "&#xe56e;" => "Streetview",
        "&#xe257;" => "Strikethrough S",
        "&#xe41d;" => "Style",
        "&#xe5d9;" => "Subdirectory Arrow Left",
        "&#xe5da;" => "Subdirectory Arrow Right",
        "&#xe8d2;" => "Subject",
        "&#xe064;" => "Subscriptions",
        "&#xe048;" => "Subtitles",
        "&#xe56f;" => "Subway",
        "&#xe8d3;" => "Supervisor Account",
        "&#xe049;" => "Surround Sound",
        "&#xe0d7;" => "Swap Calls",
        "&#xe8d4;" => "Swap Horiz",
        "&#xe8d5;" => "Swap Vert",
        "&#xe8d6;" => "Swap Vertical Circle",
        "&#xe41e;" => "Switch Camera",
        "&#xe41f;" => "Switch Video",
        "&#xe627;" => "Sync",
        "&#xe628;" => "Sync Disabled",
        "&#xe629;" => "Sync Problem",
        "&#xe62a;" => "System Update",
        "&#xe8d7;" => "System Update Alt",
        "&#xe8d8;" => "Tab",
        "&#xe8d9;" => "Tab Unselected",
        "&#xe32f;" => "Tablet",
        "&#xe330;" => "Tablet Android",
        "&#xe331;" => "Tablet Mac",
        "&#xe420;" => "Tag Faces",
        "&#xe62b;" => "Tap And Play",
        "&#xe564;" => "Terrain",
        "&#xe262;" => "Text Fields",
        "&#xe165;" => "Text Format",
        "&#xe0d8;" => "Textsms",
        "&#xe421;" => "Texture",
        "&#xe8da;" => "Theaters",
        "&#xe8db;" => "Thumb Down",
        "&#xe8dc;" => "Thumb Up",
        "&#xe8dd;" => "Thumbs Up Down",
        "&#xe62c;" => "Time To Leave",
        "&#xe422;" => "Timelapse",
        "&#xe922;" => "Timeline",
        "&#xe425;" => "Timer",
        "&#xe423;" => "Timer 10",
        "&#xe424;" => "Timer 3",
        "&#xe426;" => "Timer Off",
        "&#xe264;" => "Title",
        "&#xe8de;" => "Toc",
        "&#xe8df;" => "Today",
        "&#xe8e0;" => "Toll",
        "&#xe427;" => "Tonality",
        "&#xe913;" => "Touch App",
        "&#xe332;" => "Toys",
        "&#xe8e1;" => "Track Changes",
        "&#xe565;" => "Traffic",
        "&#xe570;" => "Train",
        "&#xe571;" => "Tram",
        "&#xe572;" => "Transfer Within A Station",
        "&#xe428;" => "Transform",
        "&#xe8e2;" => "Translate",
        "&#xe8e3;" => "Trending Down",
        "&#xe8e4;" => "Trending Flat",
        "&#xe8e5;" => "Trending Up",
        "&#xe429;" => "Tune",
        "&#xe8e6;" => "Turned In",
        "&#xe8e7;" => "Turned In Not",
        "&#xe333;" => "Tv",
        "&#xe169;" => "Unarchive",
        "&#xe166;" => "Undo",
        "&#xe5d6;" => "Unfold Less",
        "&#xe5d7;" => "Unfold More",
        "&#xe923;" => "Update",
        "&#xe1e0;" => "Usb",
        "&#xe8e8;" => "Verified User",
        "&#xe258;" => "Vertical Align Bottom",
        "&#xe259;" => "Vertical Align Center",
        "&#xe25a;" => "Vertical Align Top",
        "&#xe62d;" => "Vibration",
        "&#xe070;" => "Video Call",
        "&#xe071;" => "Video Label",
        "&#xe04a;" => "Video Library",
        "&#xe04b;" => "Videocam",
        "&#xe04c;" => "Videocam Off",
        "&#xe338;" => "Videogame Asset",
        "&#xe8e9;" => "View Agenda",
        "&#xe8ea;" => "View Array",
        "&#xe8eb;" => "View Carousel",
        "&#xe8ec;" => "View Column",
        "&#xe42a;" => "View Comfy",
        "&#xe42b;" => "View Compact",
        "&#xe8ed;" => "View Day",
        "&#xe8ee;" => "View Headline",
        "&#xe8ef;" => "View List",
        "&#xe8f0;" => "View Module",
        "&#xe8f1;" => "View Quilt",
        "&#xe8f2;" => "View Stream",
        "&#xe8f3;" => "View Week",
        "&#xe435;" => "Vignette",
        "&#xe8f4;" => "Visibility",
        "&#xe8f5;" => "Visibility Off",
        "&#xe62e;" => "Voice Chat",
        "&#xe0d9;" => "Voicemail",
        "&#xe04d;" => "Volume Down",
        "&#xe04e;" => "Volume Mute",
        "&#xe04f;" => "Volume Off",
        "&#xe050;" => "Volume Up",
        "&#xe0da;" => "Vpn Key",
        "&#xe62f;" => "Vpn Lock",
        "&#xe1bc;" => "Wallpaper",
        "&#xe002;" => "Warning",
        "&#xe334;" => "Watch",
        "&#xe924;" => "Watch Later",
        "&#xe42c;" => "Wb Auto",
        "&#xe42d;" => "Wb Cloudy",
        "&#xe42e;" => "Wb Incandescent",
        "&#xe436;" => "Wb Iridescent",
        "&#xe430;" => "Wb Sunny",
        "&#xe63d;" => "Wc",
        "&#xe051;" => "Web",
        "&#xe069;" => "Web Asset",
        "&#xe16b;" => "Weekend",
        "&#xe80e;" => "Whatshot",
        "&#xe1bd;" => "Widgets",
        "&#xe63e;" => "Wifi",
        "&#xe1e1;" => "Wifi Lock",
        "&#xe1e2;" => "Wifi Tethering",
        "&#xe8f9;" => "Work",
        "&#xe25b;" => "Wrap Text",
        "&#xe8fa;" => "Youtube Searched For",
        "&#xe8ff;" => "Zoom In",
        "&#xe900;" => "Zoom Out",
        "&#xe56b;" => "Zoom Out Map",
    );

}


